### ISSUE TITLE
Installation in docker returns "file not found"

### ISSUE THREAD

**Issue by neomaximus2k** [akaunting/akaunting#1310]
I have setup a docker compose image for testing purposes, however after install if I visit the URL I get a file not found error.

docker-compose.yml
```
version: '2'

services:
    nginx:
      image: nginx:1.13.12
      ports:
        - "8443:443"
        - "8080:80"
      volumes:
        - ./:/var/www
        - ./docker/nginxconf:/etc/nginx/conf.d
        - ./docker/ssl-cert:/etc/nginx/certs
      working_dir: /var/www
      links:
        - php
    php:
        build:
            context: ./
            dockerfile: docker/app.docker
        volumes:
            - ./:/var/www
        depends_on:
          - db
        links:
            - db
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=db"
    db:
        image: mariadb
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=dockerApp"
        ports:
            - "33061:3306"
```
app.docker
```
FROM php:7.3-fpm

RUN apt-get update
RUN apt-get install -y libmcrypt-dev mariadb-client libmcrypt4 \
	libicu-dev \
	libbz2-dev \
	libpng-dev \
	libjpeg-dev \
	libzip-dev \
	libxml2-dev \
	curl  \
	zip
	
RUN docker-php-ext-install pdo_mysql \
	bcmath \ 
	ctype \
	gd \
	json \
	mbstring \
	tokenizer \
	xml \
	zip

RUN kill -USR2 1

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# install npm
RUN curl -sL https://deb.nodesource.com/setup_13.x | bash -
RUN apt-get install -y nodejs

WORKDIR /var/www

# do a composer install and an npm install
#RUN composer install
#RUN npm install

# now install akaunting
#RUN php artisan install --db-host=db --db-port=3306 --db-name="dockerApp" --db-username="root" --db-password="secret" --admin-email="admin@company.com" --admin-password="123456"
```

the composer install ran fine, the npm install shows 14 vulnerabilites but everything installed and I ran the php install with the revised host and that works fine as well.
